apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: acme-explorer-api-horizontal-pod-autoescaler
  namespace: production
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: acme-explorer-api-deployment
  targetCPUUtilizationPercentage: 50