version: '3.7'
services:
  acme-explorer-api:
    ports:
      - "${PORT:-8081}:8080"
    environment:
      - NODE_ENV=production
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27018
      - MONGO_DB_USER=user
      - MONGO_DB_PASSWORD=S3cret
      - MONGO_DB_NAME=acme_explorer
      - API_PORT=8080
  mongodb:
    ports:
      - '27018:27017'
