version: '3.7'
services:
  acme-explorer-api:
    #build: ../
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    restart: on-failure
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
      - MONGO_DB_USER=user
      - MONGO_DB_PASSWORD=S3cret
      - MONGO_DB_NAME=acme_explorer
      - API_PORT=${API_PORT:-8080}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_ADMIN_PRIVATE_KEY=${FIREBASE_ADMIN_PRIVATE_KEY}
    depends_on:
      - mongodb
    volumes:
      - logging:/usr/src/app/logs
  mongodb:
    image: "mongo"
    command: --logpath /var/log/mongodb/db.log
    ports:
      - '${MONGO_DB_PORT:-27017}:27017'
    volumes:
      - mongodbdata:/data/db
      - logging:/var/log/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
      - MONGO_INITDB_DATABASE=acme_explorer
volumes:
  mongodbdata:
  logging:
