#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: #@ data.values.MONGO_PV_NAME
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mongo"