#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: #@ data.values.INGRESS_HTTP_PORT
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: ingress-nginx