openapi: 3.0.3
info:
  title: ACME EXPLORER - API
  description: FINAL PROJECT
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /v1/actors:
    get:
      tags:
        - Actors
      summary: Find actors
      responses:
        '200':
          description: Actors successfully retrieved.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Actor not found.
        '500':
          description: Error trying to get all actors.
    post:
      tags:
        - Actors
      summary: Create an actor
      responses:
        '200':
          description: Actors successfully created.
        '400':
          description: Error trying to create the actor. Bad Request.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '409':
          description: Email is already registered.
        '422':
          description: Validation error.
        '500':
          description: Error trying to create actor.

  /v1/actors/{actorId}:
    get:
      tags:
        - Actors
      summary: Find actor by Id
      parameters:
        - name: actorId
          in: path
          description: ID of actor to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Actor successfully retrieved.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Actor not found.
        '500':
          description: Error trying to get eligible actor.
    put:
      tags:
        - Actors
      summary: Update an actor
      parameters:
        - name: actorId
          in: path
          description: ID of actor to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Actors successfully updated.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Actor not found.
        '409':
          description: Email is already registered.
        '422':
          description: Validation error.
        '500':
          description: Error trying to update actor.
    delete:
      tags:
        - Actors
      summary: Delete an actor
      parameters:
        - name: actorId
          in: path
          description: ID of actor to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Actors successfully deleted.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Actor not found.
        '500':
          description: Error trying to delete actor.
  
  /v1/actors/{actorId}/activated:    
    patch:
      tags:
        - Actors
      summary: Enable an actor
      parameters:
        - name: actorId
          in: path
          description: ID of actor to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Actors successfully enabled.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Actor not found.
        '500':
          description: Error trying to update actor.
  
  /v1/trips:
    get:
      tags:
        - Trips
      summary: Find Trips
      responses:
        '200':
          description: Trips successfully retrieved.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Trip not found.
        '500':
          description: Error trying to get all trips.
    post:
      tags:
        - Trips
      summary: Create a trip
      responses:
        '200':
          description: Trip successfully created.
        '400':
          description: Error trying to create the trip. Bad Request.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '409':
          description: Email is already registered.
        '422':
          description: Validation error.
        '500':
          description: Error trying to create trip.

  /v1/trips/{tripId}:
    get:
      tags:
        - Trips
      summary: Find trip by Id
      parameters:
        - name: tripId
          in: path
          description: ID of trip to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Trip successfully retrieved.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Trip not found.
        '500':
          description: Error trying to get eligible trip.
    put:
      tags:
        - Trips
      summary: Update a trip
      parameters:
        - name: tripId
          in: path
          description: ID of trip to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Trip successfully updated.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Trip not found.
        '409':
          description: Email is already registered.
        '422':
          description: Validation error.
        '500':
          description: Error trying to update trip.
    delete:
      tags:
        - Trips
      summary: Delete a trip
      parameters:
        - name: tripId
          in: path
          description: ID of trip to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Trip successfully deleted.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Trip not found.
        '500':
          description: Error trying to delete trip.

  /v1/trips/{tripId}/search:
    get:
      tags:
        - Trips
      summary: Find searched trip by Id
      parameters:
        - name: tripId
          in: path
          description: ID of trip to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Searched trip successfully retrieved.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Trip not found.
        '500':
          description: Error trying to get eligible trip.

  /v1/applications:
    get:
      tags:
        - Applications
      summary: Find Applications
      responses:
        '200':
          description: Applications successfully retrieved.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Application not found.
        '500':
          description: Error trying to get all applications.
    post:
      tags:
        - Applications
      summary: Create an application
      responses:
        '200':
          description: Application successfully created.
        '400':
          description: Error trying to create the application. Bad Request.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '409':
          description: Email is already registered.
        '422':
          description: Validation error.
        '500':
          description: Error trying to create application.

  /v1/applications/{applicationId}:
    get:
      tags:
        - Applications
      summary: Find application by Id
      parameters:
        - name: applicationId
          in: path
          description: ID of application to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Application successfully retrieved.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Application not found.
        '500':
          description: Error trying to get eligible application.
    put:
      tags:
        - Applications
      summary: Update an application
      parameters:
        - name: applicationId
          in: path
          description: ID of aplication to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Application successfully updated.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Application not found.
        '409':
          description: Email is already registered.
        '422':
          description: Validation error.
        '500':
          description: Error trying to update application.
    delete:
      tags:
        - Applications
      summary: Delete an application
      parameters:
        - name: applicationId
          in: path
          description: ID of application to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Application successfully deleted.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Application not found.
        '500':
          description: Error trying to delete application.

  /v1/applications/{applicationId}/denied:
    get:
      tags:
        - Applications
      summary: Deny application by Id
      parameters:
        - name: applicationId
          in: path
          description: ID of application to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Application successfully denied.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Application not found.
        '500':
          description: Error trying to deny eligible application.

  /v1/applications/{applicationId}/approved:
    get:
      tags:
        - Applications
      summary: Approve application by Id
      parameters:
        - name: applicationId
          in: path
          description: ID of application to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Application successfully approved.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Application not found.
        '500':
          description: Error trying to approve eligible application.

  /v1/sponsorships:
    get:
      tags:
        - Sponsorships
      summary: Find Sponsorships
      responses:
        '200':
          description: Sponsorships successfully retrieved.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Sponsorship not found.
        '500':
          description: Error trying to get all Sponsorships.
    post:
      tags:
        - Sponsorships
      summary: Create a sponsorship
      responses:
        '200':
          description: Sponsorship successfully created.
        '400':
          description: Error trying to create the Sponsorship. Bad Request.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '409':
          description: Email is already registered.
        '422':
          description: Validation error.
        '500':
          description: Error trying to create Sponsorship.

  /v1/sponsorships/{sponsorshipId}:
    get:
      tags:
        - Sponsorships
      summary: Get a Sponsorship
      parameters:
        - name: sponsorshipId
          in: path
          description: ID of sponsorship to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sponsorship successfully retrieved.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Sponsorship not found.
        '409':
          description: Email is already registered.
        '422':
          description: Validation error.
        '500':
          description: Error trying to get sponsorship.
    put:
      tags:
        - Sponsorships
      summary: Update a Sponsorship
      parameters:
        - name: sponsorshipId
          in: path
          description: ID of sponsorship to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sponsorship successfully updated.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Sponsorship not found.
        '409':
          description: Email is already registered.
        '422':
          description: Validation error.
        '500':
          description: Error trying to update sponsorship.
    delete:
      tags:
        - Sponsorships
      summary: Delete a sponsorship
      parameters:
        - name: sponsorshipId
          in: path
          description: ID of sponsorship to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sponsorship successfully deleted.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Sponsorship not found.
        '500':
          description: Error trying to delete sponsorship.

  /v1/sponsorships/{sponsorshipId}/denied:
    patch:
      tags:
        - Sponsorships
      summary: Deny a Sponsorship
      parameters:
        - name: sponsorshipId
          in: path
          description: ID of sponsorship to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sponsorship successfully dennied.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Sponsorship not found.
        '409':
          description: Email is already registered.
        '422':
          description: Validation error.
        '500':
          description: Error trying to deny sponsorship.

  /v1/sponsorships/{sponsorshipId}/approved:
    patch:
      tags:
        - Sponsorships
      summary: Approve a Sponsorship
      parameters:
        - name: sponsorshipId
          in: path
          description: ID of sponsorship to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sponsorship successfully approve.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Sponsorship not found.
        '409':
          description: Email is already registered.
        '422':
          description: Validation error.
        '500':
          description: Error trying to approve sponsorship.

  /v1/finder:
    get:
      tags:
        - Finder
      summary: Find Finder
      responses:
        '200':
          description: Finder successfully retrieved.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Finder not found.
        '500':
          description: Error trying to get all Finder.
    post:
      tags:
        - Finder
      summary: Create a Finder
      responses:
        '200':
          description: Finder successfully created.
        '400':
          description: Error trying to create the Finder. Bad Request.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '409':
          description: Email is already registered.
        '422':
          description: Validation error.
        '500':
          description: Error trying to create Finder.

  /v1/finder/{finderId}:
    put:
      tags:
        - Finder
      summary: Update a Finder
      parameters:
        - name: finderId
          in: path
          description: ID of finder to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Finder successfully updated.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Finder not found.
        '409':
          description: Email is already registered.
        '422':
          description: Validation error.
        '500':
          description: Error trying to update finder.
    delete:
      tags:
        - Finder
      summary: Delete a finder
      parameters:
        - name: finderId
          in: path
          description: ID of finder to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Finder successfully deleted.
        '401':
          description: Unauthorized.
        '403':
          description: You don't have right role to carry out this operation.
        '404':
          description: Finder not found.
        '500':
          description: Error trying to delete finder.

components:    
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      