openapi: 3.0.3
info:
  title: ACME EXPLORER - API
  description: FINAL PROJECT
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /v1/actors:
    get:
      tags:
        - Actors
      summary: Find actors
      responses:
        '200':
          description: Successful